sudo: required
services:
    - docker

before_install:
- docker build -t pablitod79/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true pablitod79/react-test npm test

after_success:
    - docker build -t pablitod79/multi-client -f ./client
    - docker build -t pablitod79/multi-nginx -f ./nginx
    - docker build -t pablitod79/multi-server -f ./server
    - docker build -t pablitod79/multi-worker -f ./worker

    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
    # Take images and push theem to docker hub
    - docker push pablitod79/multi-client
    - docker push pablitod79/multi-nginx 
    - docker push pablitod79/multi-server
    - docker push pablitod79/multi-worker

